# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe028affa20e4d82306f13d33d4ad8ee4fcad4c653625b52fd2af2e89aa01f2729e3f53b246f66e34a09e30dfc16bd1185ba7523b018da455b95b71ea29fa06

test:
  secret_key_base: 5da22658d24a5ed88d3087bd0b5fae3626914e7fa4e9d760e695516d6d2debb3318e09828fbbd942f6b5dac6d6760ae68bebf86923c2ad102d092e04d094782f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
